spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batnew
    username: root
    password: 12345678
  #Redis配置
  data:
    redis:
      host: localhost
      port: 6379

  #阿里云OSS配置
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIOSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET:}
    bucket-name: bat-manager

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 驼峰命名
  mapper-locations: classpath*:Mapper/*.xml
